trigger:
  branches:
    include:
      - main
  paths:
    include:
      - helm-chart
      - pipelines/helm-chart-azure-pipelines.yaml
    exclude:
      - main.tf
      - pipelines/terraform-azure-pipelines.yaml

pool:
  vmImage: ubtuntu-latest

variables:
- group: azure_credentials

stages:
- stage: HelmDeploy
  jobs:
  - job: helmdeploy
    variables:
      - name: helmReleaseName
        value: 'bestapiever-helm-$(Build.BuildId)'
    pool:
      name: jamie-local-pool
    steps:
    - task: HelmDeploy@0
      displayName: 'Helm install'
      # timeoutInMinutes: 10
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Jamie-Azure-Service-Connection'
        azureResourceGroup: 'jamie-code-challenge'
        kubernetesCluster: 'code-challenge-eks'
        # namespace: $(kubernetesNamespace)
        command: install
        arguments: --set env.APIKEY=$(env.APIKEY)
        chartType: FilePath
        chartPath: helm-chart
        releaseName: $(helmReleaseName)
    # - task: HelmDeploy@0
    #   inputs:
    #     connectionType: 'Azure Resource Manager'
    #     azureSubscription: 'Jamie-Azure-Service-Connection'
    #     azureResourceGroup: 'jamie-code-challenge'
    #     kubernetesCluster: 'code-challenge-eks'
    #     command: 'install'
    #     chartType: 'Name'