trigger:
- main

pool:
  vmImage: ubtuntu-latest

variables:
- group: azure_credentials

stages:
- stage: HelmDeploy
  jobs:
  - job: helmdeploy
    pool:
      name: jamie-local-pool
    steps:
    - task: HelmDeploy@0
      displayName: Helm Deploy
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Jamie-Azure-Service-Connection'
        azureResourceGroup: 'jamie-code-challenge'
        kubernetesCluster: 'code-challenge-eks'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '.'
        releaseName: 'bestapiever'
        overrideValues: 'env.APIKEY=$(APIKEY)'
        