trigger:
- main

pool:
  vmImage: ubtuntu-latest

variables:
- group: azure_credentials

steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Jamie-Azure-Service-Connection'
    azureResourceGroup: 'jamie-code-challenge'
    kubernetesCluster: 'code-challenge-eks'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(build.stagingdirectory)/helm-chart/'
    releaseName: 'bestapiever'
    overrideValues: 'env.APIKEY=$(APIKEY)'