trigger:
  branches:
    include:
      - main
  paths:
    include:
      - helm-chart
      - pipelines/helm-chart-azure-pipelines.yaml
    exclude:
      - main.tf
      - pipelines/terraform-azure-pipelines.yaml

pool:
  vmImage: ubtuntu-latest

variables:
- group: azure_credentials

stages:
- stage: HelmDeploy
  jobs:
  - job: helmdeploy
    variables:
      - name: helmReleaseName
        value: 'bestapiever-helm-$(Build.BuildId)'
    pool:
      name: jamie-local-pool
    steps:

    - task: HelmDeploy@0
      displayName: 'Helm install'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'Jamie-Azure-AKS-Connection'
        command: 'install'
        chartType: 'FilePath'
        chartPath: 'helm-chart'
        releaseName: 'bestapiever-helm'
        overrideValues: 'env.APIKEY=$(env.APIKEY)'
        waitForExecution: false